// 在飞牛专属空数据库运行：BRAND_UPGRADE_ISOLATED=true node test/brand-upgrade.cjs
const assert = require('node:assert/strict')
const { randomBytes } = require('node:crypto')
const { PrismaClient } = require('@prisma/client')
const { BRAND_NAME, BRAND_SLOGAN, BRAND_SLOGAN_LINES } = require('@ai-learning-hub/contracts')
const { upgradeBrand } = require('../dist/modules/persistence/upgrade-brand')
const { bootstrapApplication } = require('../dist/modules/persistence/bootstrap')
const url = new URL(process.env.DATABASE_URL || 'file:///missing')
assert.equal(process.env.BRAND_UPGRADE_ISOLATED, 'true')
assert.equal(url.pathname, '/brand_upgrade')
const db = new PrismaClient()
const config = { brandName: 'AI MAKER CAMPUS', brandSubtitle: '高校 AI 创客学习平台', titleFirst: '加入 AI 创客社区', titleSecond: '一起学习 · 实践 · 成长', image: 'heroArms', description: '已发布说明' }
const snapshot = (config) => ({ moduleKey: 'landing_hero', config, enabled: true, items: [{ targetType: 'lab', targetId: 'preserved-reference' }] })
const report = []
async function reset() {
  await db.homepagePublication.deleteMany()
  await db.homepageModule.deleteMany()
  await db.systemSetting.deleteMany({ where: { key: { in: ['platform_name', 'platform_subtitle', 'settings_version'] } } })
}
async function fixture(pending = false, custom = false, source = config) {
  const published = snapshot(source)
  const draft = snapshot({ ...source, description: '尚未发布的人工修改', ...(custom ? { brandSubtitle: '自定义口号' } : {}) })
  const module = await db.homepageModule.create({ data: { moduleKey: 'landing_hero', name: '首屏设置', status: pending ? 'draft' : 'published', config: pending ? draft.config : source } })
  const v1 = await db.homepageModuleVersion.create({ data: { moduleId: module.id, versionNo: 1, snapshot: published } })
  const v2 = pending ? await db.homepageModuleVersion.create({ data: { moduleId: module.id, versionNo: 2, snapshot: draft } }) : v1
  await db.homepageModule.update({ where: { id: module.id }, data: { currentDraftVersionId: v2.id, publishedVersionId: v1.id } })
  const pub = await db.homepagePublication.create({ data: { version: 7, snapshot: [published] } })
  return { module, v1, v2, pub }
}
async function main() {
  assert.equal(await db.user.count(), 0, '只允许专属空库')
  assert.equal(await db.homepageModule.count(), 0, '只允许专属空库')
  process.env.SEED_ADMIN_EMAIL = 'brand-check@example.invalid'
  process.env.SEED_ADMIN_PASSWORD = randomBytes(24).toString('base64url') + '!aA9'
  await bootstrapApplication(db)
  const users = await db.user.findMany()
  const roles = await db.userRole.findMany()
  assert.equal((await db.systemSetting.findUniqueOrThrow({ where: { key: 'platform_name' } })).value, BRAND_NAME)
  assert.equal((await db.systemSetting.findUniqueOrThrow({ where: { key: 'platform_subtitle' } })).value, BRAND_SLOGAN)
  await bootstrapApplication(db)
  assert.deepEqual(await db.user.findMany(), users)
  assert.deepEqual(await db.userRole.findMany(), roles)
  report.push('空库初始化及重复初始化保留账号凭据与角色')

  await reset()
  await db.systemSetting.createMany({ data: [{ key: 'platform_name', value: 'AI数智化学习平台' }, { key: 'platform_subtitle', value: '高校 AI 创客学习平台' }] })
  const old = await fixture(true, true)
  const result = await upgradeBrand(db)
  assert.equal(result.publicationVersion, 8)
  assert.equal(result.publishedVersions, 1)
  assert.equal(result.draftVersions, 1)
  assert.ok(result.preservedCustomFields.includes('draft.landing_hero.brandSubtitle'))
  const module = await db.homepageModule.findUniqueOrThrow({ where: { id: old.module.id }, include: { currentDraftVersion: true, publishedVersion: true } })
  assert.equal(module.status, 'draft')
  assert.equal(module.config.description, '尚未发布的人工修改')
  assert.equal(module.config.brandSubtitle, '自定义口号')
  assert.equal(module.currentDraftVersion.snapshot.config.description, '尚未发布的人工修改')
  assert.equal(module.publishedVersion.snapshot.config.description, '已发布说明')
  const publication = await db.homepagePublication.findFirst({ orderBy: { version: 'desc' } })
  assert.equal(publication.snapshot[0].config.brandName, BRAND_NAME)
  assert.equal(publication.snapshot[0].config.brandSubtitle, BRAND_SLOGAN)
  assert.equal([publication.snapshot[0].config.titleFirst, publication.snapshot[0].config.titleSecond].join(' '), BRAND_SLOGAN)
  assert.deepEqual(publication.snapshot[0].items, old.pub.snapshot[0].items)
  assert.deepEqual(await db.homepageModuleVersion.findUnique({ where: { id: old.v1.id } }), old.v1)
  assert.deepEqual(await db.homepageModuleVersion.findUnique({ where: { id: old.v2.id } }), old.v2)
  assert.deepEqual(await db.homepagePublication.findUnique({ where: { id: old.pub.id } }), old.pub)
  const modulesBefore = await db.homepageModule.findMany()
  const settingsBefore = await db.systemSetting.findMany({ orderBy: { key: 'asc' } })
  const again = await upgradeBrand(db)
  assert.equal(again.publishedVersions + again.draftVersions + again.settings.length + again.modules.length, 0)
  assert.deepEqual(await db.homepageModule.findMany(), modulesBefore)
  assert.deepEqual(await db.systemSetting.findMany({ orderBy: { key: 'asc' } }), settingsBefore)
  report.push('旧库升级隔离发布与草稿，保留自定义文案、关联及历史；重复执行零写入')

  await reset()
  const previousLines = ['破盒启智、交互赋能、', '数训筑基、共创未来']
  await db.systemSetting.createMany({ data: [{ key: 'platform_name', value: BRAND_NAME }, { key: 'platform_subtitle', value: previousLines.join('') }] })
  const previous = await fixture(true, true, { ...config, brandName: BRAND_NAME, brandSubtitle: previousLines.join(''), titleFirst: previousLines[0], titleSecond: previousLines[1] })
  const upgraded = await upgradeBrand(db)
  assert.deepEqual(upgraded.settings, ['platform_subtitle'])
  assert.equal(upgraded.publishedVersions, 1)
  assert.equal(upgraded.draftVersions, 1)
  assert.ok(upgraded.preservedCustomFields.includes('draft.landing_hero.brandSubtitle'))
  const current = await db.homepageModule.findUniqueOrThrow({ where: { id: previous.module.id }, include: { currentDraftVersion: true, publishedVersion: true } })
  assert.equal(current.publishedVersion.snapshot.config.titleFirst, '破盒启智、交互赋能')
  assert.equal(current.publishedVersion.snapshot.config.brandSubtitle, '破盒启智、交互赋能 数训筑基、共创未来')
  assert.equal(current.publishedVersion.snapshot.config.description, '已发布说明')
  assert.equal(current.currentDraftVersion.snapshot.config.description, '尚未发布的人工修改')
  assert.equal(current.currentDraftVersion.snapshot.config.brandSubtitle, '自定义口号')
  assert.equal(current.currentDraftVersion.snapshot.config.titleFirst, BRAND_SLOGAN_LINES[0])
  assert.deepEqual(await db.homepageModuleVersion.findUnique({ where: { id: previous.v1.id } }), previous.v1)
  assert.deepEqual(await db.homepageModuleVersion.findUnique({ where: { id: previous.v2.id } }), previous.v2)
  assert.deepEqual(await db.homepagePublication.findUnique({ where: { id: previous.pub.id } }), previous.pub)
  const same = await upgradeBrand(db)
  assert.equal(same.settings.length + same.modules.length + same.publishedVersions + same.draftVersions, 0)
  report.push('v0.1.2 口号升级去除行末顿号，发布与自定义草稿隔离，历史保留且重复执行零写入')

  await reset()
  await fixture()
  const concurrent = await Promise.all([upgradeBrand(db), upgradeBrand(db)])
  assert.equal(concurrent.reduce((sum, r) => sum + r.publishedVersions, 0), 1)
  assert.equal(await db.homepagePublication.count(), 2)
  const joined = await db.homepageModule.findUniqueOrThrow({ where: { moduleKey: 'landing_hero' } })
  assert.equal(joined.currentDraftVersionId, joined.publishedVersionId)
  report.push('并发升级只创建一个发布版本，无待发布草稿时保持指针一致')

  await reset()
  await db.systemSetting.create({ data: { key: 'platform_name', value: 'AI MAKER CAMPUS' } })
  const broken = await db.homepagePublication.create({ data: { version: 1, snapshot: { invalid: true } } })
  await assert.rejects(upgradeBrand(db), /门户发布快照无效/)
  assert.equal((await db.systemSetting.findUniqueOrThrow({ where: { key: 'platform_name' } })).value, 'AI MAKER CAMPUS')
  assert.equal(await db.systemSetting.count({ where: { key: 'settings_version' } }), 0)
  await db.homepagePublication.delete({ where: { id: broken.id } })
  await upgradeBrand(db)
  assert.equal((await db.systemSetting.findUniqueOrThrow({ where: { key: 'platform_name' } })).value, BRAND_NAME)
  await db.systemSetting.update({ where: { key: 'platform_name' }, data: { value: '自定义平台名称' } })
  assert.ok((await upgradeBrand(db)).preservedCustomFields.includes('settings.platform_name'))
  assert.equal((await db.systemSetting.findUniqueOrThrow({ where: { key: 'platform_name' } })).value, '自定义平台名称')
  assert.deepEqual(await db.user.findMany(), users)
  assert.deepEqual(await db.userRole.findMany(), roles)
  assert.equal(BRAND_SLOGAN_LINES.join(' '), BRAND_SLOGAN)
  report.push('失败事务回滚、重试成功、自定义设置与账号关联保持不变')
  console.log(JSON.stringify({ passed: true, scenarios: report }, null, 2))
}
main().catch((error) => { console.error(error); process.exitCode = 1 }).finally(() => db.$disconnect())
